name: Build and test the API
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "**.cs"
      - "**.csproj"

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger trx --results-directory ./test-results

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.trx
